name: Run Birthday Bot

on:
  schedule:
    # Runs at 7 AM UTC (8 AM MEZ / 9 AM MESZ)
    - cron: '0 7 * * 1-5'
  workflow_dispatch: # Allows manual triggering of the workflow


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt GPG file
        run: |
          gpg --batch --yes --pinentry-mode loopback --passphrase="${{ secrets.GPG_PASSPHRASE }}" \
          --decrypt --output birthdays.csv birthdays.csv.gpg
          python3 bday_bot.py
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
